language: csharp
solution: ChargebackSdkForNet.sln
notifications:
  email:
    - sdksupport@vantiv.com
dotnet: 2.0.5
install:
  - dotnet restore
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ChargebackSdkForNet.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ChargebackSdkForNet.nunit
