language: csharp
solution: ChargebackSdkForNet.sln
notifications:
  email:
    - sdksupport@vantiv.com
dotnet: 2.1
install:
  - nuget restore ChargebackSdkForNet.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ChargebackSdkForNet.sln
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.clr4.exe  ChargebackSdkForNetTest/bin/Release/ChargebackSdkForNetTest.dll
