language: csharp
solution: ChargebackSdkForNet.sln
notifications:
  email:
    - sdksupport@vantiv.com
dotnet: 2.1
install:
  - nuget restore ChargebackSdkForNet.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - dotnet restore
  - msbuild /p:Configuration=Release ChargebackSdkForNet.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./ChargebackSdkForNetTest/bin/Release/ChargebackSdkForNetTest.dll