using System.Xml.Serialization;

namespace ChargebackSdkForNet
{
    //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://www.vantivcnp.com/chargebacks")]
[XmlRoot(Namespace="http://www.vantivcnp.com/chargebacks", IsNullable=false)]
public partial class chargebackRetrievalResponse {
    
    private long transactionIdField;
    
    private bool transactionIdFieldSpecified;
    
    private chargebackApiCase[] chargebackCaseField;
    
    /// <remarks/>
    public long transactionId {
        get {
            return this.transactionIdField;
        }
        set {
            this.transactionIdField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool transactionIdSpecified {
        get {
            return this.transactionIdFieldSpecified;
        }
        set {
            this.transactionIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("chargebackCase")]
    public chargebackApiCase[] chargebackCase {
        get {
            return this.chargebackCaseField;
        }
        set {
            this.chargebackCaseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://www.vantivcnp.com/chargebacks")]
public partial class chargebackApiCase {
    
    private long caseIdField;
    
    private bool caseIdFieldSpecified;
    
    private long merchantIdField;
    
    private bool merchantIdFieldSpecified;
    
    private System.DateTime dayIssuedByBankField;
    
    private bool dayIssuedByBankFieldSpecified;
    
    private System.DateTime dateReceivedByVantivCnpField;
    
    private bool dateReceivedByVantivCnpFieldSpecified;
    
    private long vantivCnpTxnIdField;
    
    private bool vantivCnpTxnIdFieldSpecified;
    
    private string cycleField;
    
    private string orderIdField;
    
    private string cardNumberLast4Field;
    
    private string cardTypeField;
    
    private long chargebackAmountField;
    
    private bool chargebackAmountFieldSpecified;
    
    private string chargebackCurrencyTypeField;
    
    private System.DateTime originalTxnDayField;
    
    private bool originalTxnDayFieldSpecified;
    
    private string chargebackTypeField;
    
    private long representedAmountField;
    
    private bool representedAmountFieldSpecified;
    
    private string representedCurrencyTypeField;
    
    private string reasonCodeField;
    
    private string reasonCodeDescriptionField;
    
    private string currentQueueField;
    
    private string fraudNotificationStatusField;
    
    private string acquirerReferenceNumberField;
    
    private string chargebackReferenceNumberField;
    
    private long preArbitrationAmountField;
    
    private bool preArbitrationAmountFieldSpecified;
    
    private string preArbitrationCurrencyTypeField;
    
    private string merchantTxnIdField;
    
    private string fraudNotificationDateField;
    
    private string binField;
    
    private string tokenField;
    
    private long historicalWinPercentageField;
    
    private bool historicalWinPercentageFieldSpecified;
    
    private string customerIdField;
    
    private long paymentAmountField;
    
    private bool paymentAmountFieldSpecified;
    
    private long paymentSecondaryAmountField;
    
    private bool paymentSecondaryAmountFieldSpecified;
    
    private System.DateTime replyByDayField;
    
    private bool replyByDayFieldSpecified;
    
    private chargebackApiActivity[] activityField;
    
    /// <remarks/>
    public long caseId {
        get {
            return this.caseIdField;
        }
        set {
            this.caseIdField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool caseIdSpecified {
        get {
            return this.caseIdFieldSpecified;
        }
        set {
            this.caseIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public long merchantId {
        get {
            return this.merchantIdField;
        }
        set {
            this.merchantIdField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool merchantIdSpecified {
        get {
            return this.merchantIdFieldSpecified;
        }
        set {
            this.merchantIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(DataType="date")]
    public System.DateTime dayIssuedByBank {
        get {
            return this.dayIssuedByBankField;
        }
        set {
            this.dayIssuedByBankField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool dayIssuedByBankSpecified {
        get {
            return this.dayIssuedByBankFieldSpecified;
        }
        set {
            this.dayIssuedByBankFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(DataType="date")]
    public System.DateTime dateReceivedByVantivCnp {
        get {
            return this.dateReceivedByVantivCnpField;
        }
        set {
            this.dateReceivedByVantivCnpField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool dateReceivedByVantivCnpSpecified {
        get {
            return this.dateReceivedByVantivCnpFieldSpecified;
        }
        set {
            this.dateReceivedByVantivCnpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public long vantivCnpTxnId {
        get {
            return this.vantivCnpTxnIdField;
        }
        set {
            this.vantivCnpTxnIdField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool vantivCnpTxnIdSpecified {
        get {
            return this.vantivCnpTxnIdFieldSpecified;
        }
        set {
            this.vantivCnpTxnIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string cycle {
        get {
            return this.cycleField;
        }
        set {
            this.cycleField = value;
        }
    }
    
    /// <remarks/>
    public string orderId {
        get {
            return this.orderIdField;
        }
        set {
            this.orderIdField = value;
        }
    }
    
    /// <remarks/>
    public string cardNumberLast4 {
        get {
            return this.cardNumberLast4Field;
        }
        set {
            this.cardNumberLast4Field = value;
        }
    }
    
    /// <remarks/>
    public string cardType {
        get {
            return this.cardTypeField;
        }
        set {
            this.cardTypeField = value;
        }
    }
    
    /// <remarks/>
    public long chargebackAmount {
        get {
            return this.chargebackAmountField;
        }
        set {
            this.chargebackAmountField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool chargebackAmountSpecified {
        get {
            return this.chargebackAmountFieldSpecified;
        }
        set {
            this.chargebackAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string chargebackCurrencyType {
        get {
            return this.chargebackCurrencyTypeField;
        }
        set {
            this.chargebackCurrencyTypeField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(DataType="date")]
    public System.DateTime originalTxnDay {
        get {
            return this.originalTxnDayField;
        }
        set {
            this.originalTxnDayField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool originalTxnDaySpecified {
        get {
            return this.originalTxnDayFieldSpecified;
        }
        set {
            this.originalTxnDayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string chargebackType {
        get {
            return this.chargebackTypeField;
        }
        set {
            this.chargebackTypeField = value;
        }
    }
    
    /// <remarks/>
    public long representedAmount {
        get {
            return this.representedAmountField;
        }
        set {
            this.representedAmountField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool representedAmountSpecified {
        get {
            return this.representedAmountFieldSpecified;
        }
        set {
            this.representedAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string representedCurrencyType {
        get {
            return this.representedCurrencyTypeField;
        }
        set {
            this.representedCurrencyTypeField = value;
        }
    }
    
    /// <remarks/>
    public string reasonCode {
        get {
            return this.reasonCodeField;
        }
        set {
            this.reasonCodeField = value;
        }
    }
    
    /// <remarks/>
    public string reasonCodeDescription {
        get {
            return this.reasonCodeDescriptionField;
        }
        set {
            this.reasonCodeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string currentQueue {
        get {
            return this.currentQueueField;
        }
        set {
            this.currentQueueField = value;
        }
    }
    
    /// <remarks/>
    public string fraudNotificationStatus {
        get {
            return this.fraudNotificationStatusField;
        }
        set {
            this.fraudNotificationStatusField = value;
        }
    }
    
    /// <remarks/>
    public string acquirerReferenceNumber {
        get {
            return this.acquirerReferenceNumberField;
        }
        set {
            this.acquirerReferenceNumberField = value;
        }
    }
    
    /// <remarks/>
    public string chargebackReferenceNumber {
        get {
            return this.chargebackReferenceNumberField;
        }
        set {
            this.chargebackReferenceNumberField = value;
        }
    }
    
    /// <remarks/>
    public long preArbitrationAmount {
        get {
            return this.preArbitrationAmountField;
        }
        set {
            this.preArbitrationAmountField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool preArbitrationAmountSpecified {
        get {
            return this.preArbitrationAmountFieldSpecified;
        }
        set {
            this.preArbitrationAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string preArbitrationCurrencyType {
        get {
            return this.preArbitrationCurrencyTypeField;
        }
        set {
            this.preArbitrationCurrencyTypeField = value;
        }
    }
    
    /// <remarks/>
    public string merchantTxnId {
        get {
            return this.merchantTxnIdField;
        }
        set {
            this.merchantTxnIdField = value;
        }
    }
    
    /// <remarks/>
    public string fraudNotificationDate {
        get {
            return this.fraudNotificationDateField;
        }
        set {
            this.fraudNotificationDateField = value;
        }
    }
    
    /// <remarks/>
    public string bin {
        get {
            return this.binField;
        }
        set {
            this.binField = value;
        }
    }
    
    /// <remarks/>
    public string token {
        get {
            return this.tokenField;
        }
        set {
            this.tokenField = value;
        }
    }
    
    /// <remarks/>
    public long historicalWinPercentage {
        get {
            return this.historicalWinPercentageField;
        }
        set {
            this.historicalWinPercentageField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool historicalWinPercentageSpecified {
        get {
            return this.historicalWinPercentageFieldSpecified;
        }
        set {
            this.historicalWinPercentageFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string customerId {
        get {
            return this.customerIdField;
        }
        set {
            this.customerIdField = value;
        }
    }
    
    /// <remarks/>
    public long paymentAmount {
        get {
            return this.paymentAmountField;
        }
        set {
            this.paymentAmountField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool paymentAmountSpecified {
        get {
            return this.paymentAmountFieldSpecified;
        }
        set {
            this.paymentAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public long paymentSecondaryAmount {
        get {
            return this.paymentSecondaryAmountField;
        }
        set {
            this.paymentSecondaryAmountField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool paymentSecondaryAmountSpecified {
        get {
            return this.paymentSecondaryAmountFieldSpecified;
        }
        set {
            this.paymentSecondaryAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(DataType="date")]
    public System.DateTime replyByDay {
        get {
            return this.replyByDayField;
        }
        set {
            this.replyByDayField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool replyByDaySpecified {
        get {
            return this.replyByDayFieldSpecified;
        }
        set {
            this.replyByDayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("activity")]
    public chargebackApiActivity[] activity {
        get {
            return this.activityField;
        }
        set {
            this.activityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://www.vantivcnp.com/chargebacks")]
public partial class chargebackApiActivity {
    
    private System.DateTime activityDateField;
    
    private bool activityDateFieldSpecified;
    
    private string activityTypeField;
    
    private string fromQueueField;
    
    private string toQueueField;
    
    private long settlementAmountField;
    
    private bool settlementAmountFieldSpecified;
    
    private string settlementCurrencyTypeField;
    
    private string notesField;
    
    private string assignedToField;
    
    /// <remarks/>
    [XmlElement(DataType="date")]
    public System.DateTime activityDate {
        get {
            return this.activityDateField;
        }
        set {
            this.activityDateField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool activityDateSpecified {
        get {
            return this.activityDateFieldSpecified;
        }
        set {
            this.activityDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string activityType {
        get {
            return this.activityTypeField;
        }
        set {
            this.activityTypeField = value;
        }
    }
    
    /// <remarks/>
    public string fromQueue {
        get {
            return this.fromQueueField;
        }
        set {
            this.fromQueueField = value;
        }
    }
    
    /// <remarks/>
    public string toQueue {
        get {
            return this.toQueueField;
        }
        set {
            this.toQueueField = value;
        }
    }
    
    /// <remarks/>
    public long settlementAmount {
        get {
            return this.settlementAmountField;
        }
        set {
            this.settlementAmountField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool settlementAmountSpecified {
        get {
            return this.settlementAmountFieldSpecified;
        }
        set {
            this.settlementAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string settlementCurrencyType {
        get {
            return this.settlementCurrencyTypeField;
        }
        set {
            this.settlementCurrencyTypeField = value;
        }
    }
    
    /// <remarks/>
    public string notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    public string assignedTo {
        get {
            return this.assignedToField;
        }
        set {
            this.assignedToField = value;
        }
    }
}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vantivcnp.com/chargebacks")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.vantivcnp.com/chargebacks", IsNullable=false)]
//public partial class chargebackUpdateRequest {
//    
//    private activityType activityTypeField;
//    
//    private string assignedToField;
//    
//    private string noteField;
//    
//    private long representedAmountField;
//    
//    private bool representedAmountFieldSpecified;
    
//    /// <remarks/>
//    public activityType activityType {
//        get {
//            return this.activityTypeField;
//        }
//        set {
//            this.activityTypeField = value;
//        }
//    }
//    
//    /// <remarks/>
//    public string assignedTo {
//        get {
//            return this.assignedToField;
//        }
//        set {
//            this.assignedToField = value;
//        }
//    }
//    
//    /// <remarks/>
//    public string note {
//        get {
//            return this.noteField;
//        }
//        set {
//            this.noteField = value;
//        }
//    }
//    
//    /// <remarks/>
//    public long representedAmount {
//        get {
//            return this.representedAmountField;
//        }
//        set {
//            this.representedAmountField = value;
//        }
//    }
//    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlIgnoreAttribute()]
//    public bool representedAmountSpecified {
//        get {
//            return this.representedAmountFieldSpecified;
//        }
//        set {
//            this.representedAmountFieldSpecified = value;
//        }
//    }
//}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[XmlType(Namespace="http://www.vantivcnp.com/chargebacks")]
public enum activityType {
    
    /// <remarks/>
    ASSIGN_TO_USER,
    
    /// <remarks/>
    ADD_NOTE,
    
    /// <remarks/>
    MERCHANT_ACCEPTS_LIABILITY,
    
    /// <remarks/>
    MERCHANT_REPRESENT,
    
    /// <remarks/>
    MERCHANT_RESPOND,
    
    /// <remarks/>
    MERCHANT_REQUESTS_ARBITRATION,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://www.vantivcnp.com/chargebacks")]
[XmlRoot(Namespace="http://www.vantivcnp.com/chargebacks", IsNullable=false)]
public partial class chargebackUpdateResponse {
    
    private long transactionIdField;
    
    private bool transactionIdFieldSpecified;
    
    /// <remarks/>
    public long transactionId {
        get {
            return this.transactionIdField;
        }
        set {
            this.transactionIdField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool transactionIdSpecified {
        get {
            return this.transactionIdFieldSpecified;
        }
        set {
            this.transactionIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://www.vantivcnp.com/chargebacks")]
[XmlRoot(Namespace="http://www.vantivcnp.com/chargebacks", IsNullable=false)]
public partial class errorResponse {
    
    private string[] errorsField;
    
    /// <remarks/>
    [XmlArrayItem("error", IsNullable=false)]
    public string[] errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://www.vantivcnp.com/chargebacks")]
[XmlRoot(Namespace="http://www.vantivcnp.com/chargebacks", IsNullable=false)]
public partial class chargebackDocumentUploadResponse {
    
    private long merchantIdField;
    
    private long caseIdField;
    
    private string[] documentIdField;
    
    private string responseCodeField;
    
    private string responseMessageField;
    
    /// <remarks/>
    public long merchantId {
        get {
            return this.merchantIdField;
        }
        set {
            this.merchantIdField = value;
        }
    }
    
    /// <remarks/>
    public long caseId {
        get {
            return this.caseIdField;
        }
        set {
            this.caseIdField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("documentId")]
    public string[] documentId {
        get {
            return this.documentIdField;
        }
        set {
            this.documentIdField = value;
        }
    }
    
    /// <remarks/>
    public string responseCode {
        get {
            return this.responseCodeField;
        }
        set {
            this.responseCodeField = value;
        }
    }
    
    /// <remarks/>
    public string responseMessage {
        get {
            return this.responseMessageField;
        }
        set {
            this.responseMessageField = value;
        }
    }
}

}